### ISSUE TITLE
Getting started with the contributions

### ISSUE THREAD

**Issue by LitZeus** [GeomScale/gsoc24#1]
i am tejas from india, computer engineering undergrad. i am new to open source contributions but would like to contribute to the open source projects with minimal mentorship while being conssitent.
I bring skillset of python, C++, react, tensorflow, data visualization, nltk, pytorch like technologies.

Where can i start?

**Comment by vfisikop** [comment]
This place is related to GeomScale's participation to Google Summer of Code 2024 program, which is almost over. Please have a look at contributions guidelines and issues in our code repositories.
